// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineParkingLotSystem.Infrastructure.Data;

#nullable disable

namespace OnlineParkingLotSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260625160918_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("OnlineParkingLotSystem.Domain.Entities.Floor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FloorNumber")
                        .HasColumnType("int");

                    b.Property<int>("ParkingLotId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParkingLotId");

                    b.ToTable("Floors");
                });

            modelBuilder.Entity("OnlineParkingLotSystem.Domain.Entities.ParkingLot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ParkingLots");
                });

            modelBuilder.Entity("OnlineParkingLotSystem.Domain.Entities.ParkingSpot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FloorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SpotNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("SpotType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.ToTable("ParkingSpots");

                    b.HasDiscriminator<int>("SpotType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("OnlineParkingLotSystem.Domain.Entities.ParkingTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ExitTime")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("FeePaid")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("FeeStrategyType")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ParkingSpotId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParkingSpotId");

                    b.HasIndex("VehicleId");

                    b.ToTable("ParkingTickets");
                });

            modelBuilder.Entity("OnlineParkingLotSystem.Domain.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LicensePlate")
                        .IsUnique();

                    b.ToTable("Vehicles");

                    b.HasDiscriminator<int>("VehicleType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("OnlineParkingLotSystem.Domain.Entities.CompactSpot", b =>
                {
                    b.HasBaseType("OnlineParkingLotSystem.Domain.Entities.ParkingSpot");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("OnlineParkingLotSystem.Domain.Entities.HandicappedSpot", b =>
                {
                    b.HasBaseType("OnlineParkingLotSystem.Domain.Entities.ParkingSpot");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("OnlineParkingLotSystem.Domain.Entities.LargeSpot", b =>
                {
                    b.HasBaseType("OnlineParkingLotSystem.Domain.Entities.ParkingSpot");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("OnlineParkingLotSystem.Domain.Entities.Car", b =>
                {
                    b.HasBaseType("OnlineParkingLotSystem.Domain.Entities.Vehicle");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("OnlineParkingLotSystem.Domain.Entities.Motorcycle", b =>
                {
                    b.HasBaseType("OnlineParkingLotSystem.Domain.Entities.Vehicle");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("OnlineParkingLotSystem.Domain.Entities.Truck", b =>
                {
                    b.HasBaseType("OnlineParkingLotSystem.Domain.Entities.Vehicle");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("OnlineParkingLotSystem.Domain.Entities.Floor", b =>
                {
                    b.HasOne("OnlineParkingLotSystem.Domain.Entities.ParkingLot", "ParkingLot")
                        .WithMany("Floors")
                        .HasForeignKey("ParkingLotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParkingLot");
                });

            modelBuilder.Entity("OnlineParkingLotSystem.Domain.Entities.ParkingSpot", b =>
                {
                    b.HasOne("OnlineParkingLotSystem.Domain.Entities.Floor", "Floor")
                        .WithMany("ParkingSpots")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Floor");
                });

            modelBuilder.Entity("OnlineParkingLotSystem.Domain.Entities.ParkingTicket", b =>
                {
                    b.HasOne("OnlineParkingLotSystem.Domain.Entities.ParkingSpot", "ParkingSpot")
                        .WithMany()
                        .HasForeignKey("ParkingSpotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OnlineParkingLotSystem.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("ParkingTickets")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParkingSpot");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("OnlineParkingLotSystem.Domain.Entities.Floor", b =>
                {
                    b.Navigation("ParkingSpots");
                });

            modelBuilder.Entity("OnlineParkingLotSystem.Domain.Entities.ParkingLot", b =>
                {
                    b.Navigation("Floors");
                });

            modelBuilder.Entity("OnlineParkingLotSystem.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("ParkingTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
